# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.RemoveField(
            model_name='accessoriestype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='librarytype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technologytype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wardrobetype',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Accessory Items'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library Items'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technology Items'},
        ),
        migrations.AlterModelOptions(
            name='wardrobe',
            options={'verbose_name_plural': 'Wardrobe Items'},
        ),
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='isbn',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='modelnumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='serialnumber',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='color',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessories',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
        ),
        migrations.AlterField(
            model_name='library',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
        ),
        migrations.DeleteModel(
            name='AccessoriesType',
        ),
        migrations.DeleteModel(
            name='LibraryType',
        ),
        migrations.DeleteModel(
            name='TechnologyType',
        ),
        migrations.DeleteModel(
            name='WardrobeType',
        ),
        migrations.AddField(
            model_name='brands',
            name='type',
            field=models.ManyToManyField(to='website.Types'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Brands'),
            preserve_default=False,
        ),
    ]
