# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160606_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='categories',
            field=models.ManyToManyField(to='website.Categories'),
        ),
    ]
