# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160606_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=1, max_length=200, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, max_length=200, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, max_length=200, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=1, max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
