# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160606_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='image',
            field=models.FilePathField(default=1, path='D:\\Documents\\Programming\\homecatalog/website/static/icons/fashion/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='library/'),
        ),
    ]
