# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20160804_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='image',
            field=models.FilePathField(path='/Users/arlyon/Documents/Projects/arlyon/website/static/icons/fashion/'),
        ),
    ]
