# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160814_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\arlyon/website/static/icons/fashion/'),
        ),
    ]
