# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_flag', models.FilePathField(verbose_name='D:/Documents/Programming/KerbalProgramManager/manager/static/flags')),
                ('agency_bio', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='kerbals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adddate', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionid', models.IntegerField(default=0)),
                ('plan', models.CharField(max_length=1000)),
                ('builddate', models.IntegerField(default=0)),
                ('fundsbefore', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('totaldeltav', models.IntegerField(default=0)),
                ('stages', models.IntegerField(default=0)),
                ('parts', models.IntegerField(default=0)),
                ('mass', models.IntegerField(default=0)),
                ('launchdate', models.IntegerField(default=0)),
                ('crewmembers', models.BinaryField()),
                ('summary', models.CharField(max_length=1000)),
                ('recdate', models.IntegerField(default=0)),
                ('scichange', models.IntegerField(default=0)),
                ('totalsci', models.IntegerField(default=0)),
                ('fundschange', models.IntegerField(default=0)),
                ('totalfunds', models.IntegerField(default=0)),
                ('repchange', models.IntegerField(default=0)),
                ('totalrep', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='missionstatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.FilePathField(verbose_name='D:/Documents/Programming/KerbalProgramManager/manager/static/programs')),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('deltav', models.IntegerField(default=0)),
                ('crewcapacity', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='shiptypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='ships',
            name='shiptype',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), to='program.shiptypes'),
        ),
        migrations.AddField(
            model_name='missions',
            name='launcher',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), related_name='mission_launcher', to='program.ships'),
        ),
        migrations.AddField(
            model_name='missions',
            name='programid',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), to='program.programs'),
        ),
        migrations.AddField(
            model_name='missions',
            name='ship',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), related_name='mission_ship', to='program.ships'),
        ),
        migrations.AddField(
            model_name='missions',
            name='status',
            field=models.ForeignKey(on_delete=models.SET('Unknown'), to='program.missionstatuses'),
        ),
    ]
