# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20160426_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_flag',
            field=models.FilePathField(path='D:/Documents/Programming/kml/program/static/flags'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.FilePathField(path='D:/Documents/Programming/kml/program/static/programs'),
        ),
    ]
