# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20160426_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='kerbals',
            options={'verbose_name_plural': 'Kerbals'},
        ),
        migrations.AlterModelOptions(
            name='missions',
            options={'verbose_name_plural': 'Missions'},
        ),
        migrations.AlterModelOptions(
            name='missionstatuses',
            options={'verbose_name_plural': 'Mission Statuses'},
        ),
        migrations.AlterModelOptions(
            name='mods',
            options={'verbose_name_plural': 'Mods'},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='ships',
            options={'verbose_name_plural': 'Ships'},
        ),
        migrations.AlterModelOptions(
            name='shiptypes',
            options={'verbose_name_plural': 'Ship Types'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='complexity',
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
