# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20160426_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
