# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20160426_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mods',
            name='ksp_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
