# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20160426_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='launcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Unknown'), related_name='mission_launcher', to='program.ships'),
        ),
    ]
