# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_shiptypes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_color',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
