# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_agency_agency_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerbals',
            name='career',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='shiptypes',
            name='image',
            field=models.FilePathField(default='lander.png', path='D:/Documents/Programming/kml/program/static/shiptypes'),
            preserve_default=False,
        ),
    ]
