# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_auto_20160428_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
