# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_auto_20160429_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_flag',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml/program/static/flags'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml/program/static/shiptypes'),
        ),
        migrations.AlterField(
            model_name='shiptypes',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml/program/static/shiptypes'),
        ),
    ]
