# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_auto_20160429_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml/program/static/programs'),
        ),
    ]
