# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_auto_20160429_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_flag',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml\\programs\\static\\flags'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml\\programs\\static\\programs'),
        ),
        migrations.AlterField(
            model_name='shiptypes',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\kml\\programs\\static\\shiptypes'),
        ),
    ]
