# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_auto_20160429_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='ksp_dir',
            field=models.CharField(default='D:\\Programs\\SteamLibrary\\SteamApps\\common\\Kerbal Space Program\\saves\\Kerbin Jumpwerks\\Ships\\VAB', max_length=500),
            preserve_default=False,
        ),
    ]
