# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_agency_ksp_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='ships',
            name='parts',
            field=models.IntegerField(default=0),
        ),
    ]
