# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_color',
            field=models.ForeignKey(on_delete=models.SET('red'), to='program.colors'),
        ),
    ]
