# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20160501_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='grandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Mission Grand Statuses',
            },
        ),
        migrations.AddField(
            model_name='missionstatuses',
            name='grandstatus',
            field=models.ForeignKey(default=1, on_delete=models.SET('1'), to='program.grandStatus'),
            preserve_default=False,
        ),
    ]
