# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_auto_20160502_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='deltavMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deltav', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=models.SET('Kerbin'), to='program.deltavMap')),
            ],
        ),
        migrations.CreateModel(
            name='missionNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=models.SET('Kerbin'), to='program.deltavMap')),
                ('nodeMission', models.ForeignKey(on_delete=models.SET('None'), to='program.missions')),
            ],
        ),
    ]
