# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_deltavmap_missionnodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltavmap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Kerbin'), to='program.deltavMap'),
        ),
    ]
