# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_auto_20160502_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deltavmap',
            options={'verbose_name_plural': 'Delta V Map'},
        ),
        migrations.AlterModelOptions(
            name='missionnodes',
            options={'verbose_name_plural': 'Mission Nodes'},
        ),
        migrations.RemoveField(
            model_name='missions',
            name='crewmembers',
        ),
        migrations.AddField(
            model_name='missions',
            name='crewmembers',
            field=models.ManyToManyField(to='program.kerbals'),
        ),
    ]
