# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_auto_20160821_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_flag',
            field=models.FilePathField(path='D:\\Documents\\Programming\\arlyon/program/static/flags/'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\arlyon/program/static/programs/'),
        ),
        migrations.AlterField(
            model_name='shiptypes',
            name='image',
            field=models.FilePathField(path='D:\\Documents\\Programming\\arlyon/program/static/shiptypes/'),
        ),
    ]
