# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentstatus', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=0)),
                ('requestdate', models.DateField()),
                ('buyprice', models.IntegerField(default=0)),
                ('purchasedate', models.DateField()),
                ('listeddate', models.DateField()),
                ('sellprice', models.IntegerField(default=0)),
                ('solddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.FilePathField(path='D:\\Documents\\Programming\\rscg\\rsflip/static/itemthumbs/')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pricelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pricelow', models.IntegerField(default=0)),
                ('pricehigh', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipper.item')),
            ],
        ),
        migrations.AddField(
            model_name='flip',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipper.item'),
        ),
    ]
