# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='urls',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
