# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipper', '0002_item_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='urls',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='item',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='item',
            name='itemid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='members',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
