# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipper', '0003_auto_20160512_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flip',
            options={'verbose_name_plural': 'Flips'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='pricelog',
            options={'verbose_name_plural': 'Price Logs'},
        ),
        migrations.RemoveField(
            model_name='flip',
            name='currentstatus',
        ),
        migrations.AlterField(
            model_name='flip',
            name='listeddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flip',
            name='purchasedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flip',
            name='solddate',
            field=models.DateField(null=True),
        ),
    ]
