# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipper', '0006_auto_20160513_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='icon',
        ),
        migrations.AddField(
            model_name='pricelog',
            name='buyvolume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='priceaverage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='sellvolume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
