# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipper', '0010_auto_20160824_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
